context:
  version: "0.8.2"

package:
  name: t-rec
  version: ${{ version }}

source:
  url: https://github.com/sassman/t-rec-rs/archive/v${{ version }}.tar.gz
  sha256: 79ea7cbfe88e45ab913fa9963d74b9b7530cb73e39b686b0d8a692b7a9f331b8

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - imagemagick
    - if: osx
      then: libiconv
    - if: linux
      then: xorg-libx11

tests:
  - script:
      - t-rec --help

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Blazingly fast terminal recorder that generates animated gif images for the web
  homepage: https://github.com/sassman/t-rec-rs
  repository: https://github.com/sassman/t-rec-rs

extra:
  recipe-maintainers:
    - danielnachun
